apiVersion: v1
kind: Service
metadata:
  name: dcgm-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 2.1.1
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9400'
spec:
  selector:
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/version: 2.1.1
  ports:
    - name: metrics
      port: 9400
