apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: savvihub-agent
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: savvihub-agent
  template:
    metadata:
      labels:
        name: savvihub-agent
    spec:
      containers:
        - name: savvihub-agent
          image: "savvihub/cluster-agent:latest"
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: SAVVIHUB_API_URL
              value: {{ .Values.savvihub.apiServer }}
            - name: SAVVIHUB_LOG_LEVEL
              value: {{ .Values.savvihub.logLevel }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: logcontainerpath
              readOnly: true
              mountPath: /var/lib/docker/containers
            - name: access-token
              readOnly: true
              mountPath: /secrets
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: logcontainerpath
          hostPath:
            path: /var/lib/docker/containers
        - name: access-token
          secret:
            secretName: savvihub-agent
      serviceAccountName: savvihub
