kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: savvihub
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']

{{- if not (empty .Values.preinstalledNamespace) }}
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: savvihub-exporters-{{ .Release.Name }}
  namespace: {{ .Values.preinstalledNamespace }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get", "watch"]
{{- end -}}
