kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: savvihub
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: savvihub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: savvihub
