kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: savvihub
subjects:
  - kind: ServiceAccount
    name: savvihub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: savvihub

{{- if not (empty .Values.preinstalledNamespace) }}
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: savvihub-exporters-{{ .Release.Name }}
  namespace: {{ .Values.preinstalledNamespace }}
subjects:
  - kind: ServiceAccount
    name: savvihub
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: savvihub-exporters-{{ .Release.Name }}
{{- end -}}
