kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: savvihub
  namespace: {{ .Values.namespace }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
