apiVersion: v1
kind: Secret
metadata:
  name: savvihub-agent
  namespace: {{ .Values.namespace }}
data:
  access-token: {{ required "Agent access token required." .Values.savvihub.agentAccessToken | toString | b64enc }}
type: Opaque
