apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind-{{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role-{{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: {{ .Values.namespace }}
