{{- if empty .Values.preinstalledNamespace -}}
apiVersion: v1
kind: Service
metadata:
  name: savvihub-node-exporter
  labels:
    v1.k8s.savvihub.com/managed: 'true'
    v1.k8s.savvihub.com/type: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    name: node-exporter
    phase: prod
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 9100
{{- end -}}
